name = "unitest"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["unitest"]
[[depends-on]]
legacy = "~0.1.0-dev"
[[pins]]
legacy = { path='legacy' }
[[depends-on]]
modern = "~0.1.0-dev"
[[pins]]
modern = { path='modern' }
